rules:
  slave:
    level: failure  # default rules are set to warning
  blacklist:
    level: failure
  whitelist:
    level: failure
ignore:
 - ".github/in-solidarity.yml"  # default
 - ".github/workflows/*.yml"
 - "**/*.yml"
 - "openshift_cli_installer/manifests/*.j2"
