default_language_version:
    python: python3

repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.2.1"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports

# TODO: Enable once https://github.com/hadialqattan/pycln/issues/221 is resolved
#  - repo: https://github.com/hadialqattan/pycln
#    rev: "v2.3.0"
#    hooks:
#        - id: pycln

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: "23.10.1"
    hooks:
    - id: black
      args: [--preview]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md] # Do not process Markdown files.
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-builtin-literals
    - id: check-docstring-first
    - id: check-toml

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        additional_dependencies: [
          "git+https://github.com/RedHatQE/flake8-plugins.git",
          "pep8-naming",
          "flake8-mutable",
        ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
